services:
  postgres:
    container_name: headoftp
    hostname: postgres
    image: postgres:17.10-alpine@sha256:dc17045ccfd343b49600570ea734b9c4991cf1c3f3302e67df51e3b402dd55c4
    environment:
      POSTGRES_PASSWORD: headoftp
      POSTGRES_DB: headoftp
    ports:
      - 5432:5432
