services:
  postgres:
    container_name: headoftp
    hostname: postgres
    image: postgres:17.5-alpine@sha256:6567bca8d7bc8c82c5922425a0baee57be8402df92bae5eacad5f01ae9544daa
    environment:
      POSTGRES_PASSWORD: headoftp
      POSTGRES_DB: headoftp
    ports:
      - 5432:5432
