services:
  postgres:
    container_name: headoftp
    hostname: postgres
    image: postgres:17.5-alpine@sha256:bcb90dc18910057ff49ce2ea157d8a0d534964090d39af959df41083f18c3318
    environment:
      POSTGRES_PASSWORD: headoftp
      POSTGRES_DB: headoftp
    ports:
      - 5432:5432
