services:
  postgres:
    container_name: headoftp
    hostname: postgres
    image: postgres:16.4-alpine@sha256:d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1fffdf
    environment:
      POSTGRES_PASSWORD: headoftp
      POSTGRES_DB: headoftp
    ports:
      - 5432:5432
