services:
  postgres:
    container_name: headoftp
    hostname: postgres
    image: postgres:16.4-alpine@sha256:5660c2cbfea50c7a9127d17dc4e48543eedd3d7a41a595a2dfa572471e37e64c
    environment:
      POSTGRES_PASSWORD: headoftp
      POSTGRES_DB: headoftp
    ports:
      - 5432:5432
