openapi: 3.0.3
info:
  title: Head Of TP API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: device
    description: device
paths:
  /device:
    post:
      tags:
        - device
      operationId: createDeviceLocation
      summary: Create a device location
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: false
        - in: query
          name: timestamp
          schema:
            type: string
          required: false
        - in: query
          name: lat
          schema:
            type: string
          required: false
        - in: query
          name: lon
          schema:
            type: string
          required: false
        - in: query
          name: speed
          schema:
            type: string
          required: false
        - in: query
          name: bearing
          schema:
            type: string
          required: false
        - in: query
          name: altitude
          schema:
            type: string
          required: false
        - in: query
          name: accuracy
          schema:
            type: string
          required: false
        - in: query
          name: batt
          schema:
            type: string
          required: false
      responses:
        200:
          description: Device location successfully created
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  schemas:
    ProblemDetailResponse:
      required:
        - title
        - status
        - detail
        - instance
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem type
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem
          example: 400
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem
          example: /device
