# Spring
spring:
  application:
    name: head-of-tp
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jackson:
    time-zone: Europe/Brussels

# Management
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: HEAD_OF_TP
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  server:
    port: 8888