AWSTemplateFormatVersion: "2010-09-09"
Description: Setup a S3 bucket store terraform state file to lock state

Resources:
  TerraformBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: "head-of-tp-backend-prd-terraform-state"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
Outputs:
  TerraformBucket:
    Description: The S3 bucket name wherefore your terraform state files
    Value: !Ref TerraformBucket
